vars = {
  types = {
    Typeless = "Typeless",
    Normal = "Normal",
    Fire = "Fire",
    Water = "Water",
    Electric = "Electric",
    Grass = "Grass",
    Ice = "Ice",
    Fighting = "Fighting",
    Poison = "Poison",
    Ground = "Ground",
    Flying = "Flying",
    Psychic = "Psychic",
    Bug = "Bug",
    Rock = "Rock",
    Ghost = "Ghost",
    Dragon = "Dragon",
    Dark = "Dark",
    Steel = "Steel",
    Fairy = "Fairy"
  },
  setup_panel = {
    HOS_CAMPAIGN_LABEL = "Heart of Sinnoh Campaign",
    UB_CAMPAIGN_LABEL = "Ultra Burst Campaign",
    START_GAME_LABEL = "Start Game"
  },
  music_box = {
    OFFLINE_LABEL = "Music Box",
    NOW_PLAYING_LABEL = "Now Playing: ",
    BATTLE_LABEL = "Battle! ",
    PLAY_BUTTON_TOOLTIP = "Play",
    PAUSE_BUTTON_TOOLTIP = "Pause",
    BACK_BUTTON_TOOLTIP = "Back",
    FORWARD_BUTTON_TOOLTIP = "Forward",
    SHUFFLE_BUTTON_TOOLTIP = "Toggle Shuffle",
    REPEAT_BUTTON_TOOLTIP = "Toggle Repeat"
  },
  pokedex = {
    SEARCH_BUTTON_LABEL = "Search",
    RETURN_BUTTON_LABEL = "Return",
    EVOLVE_BUTTON_LABEL = "Evolve",
    BATTLE_BUTTON_LABEL = "Battle!",
    CLOSE_BUTTON_LABEL = "Close Pokédex",
    OPEN_BUTTON_LABEL = "Open Pokédex",

    SEARCH_NOT_ON_ENCOUNTER_MESSAGE = " trainer token not on an encounter token.",
    SEARCH_OUT_OF_POKEMON_MESSAGE = "Out of Pokémon for this biome, climate and encounter tier. You may claim any Apricorns here but your turn ends.",
    RETURN_ALREADY_RUNNING_MESSAGE = "Return cards method currently running (if it is not, reloading the game should fix it).",
    EVOLVE_SLOT_MESSAGE = "Place a Pokémon in the slot above.",
    EVOLVE_RETURN_MESSAGE = "Return the currently searched Pokémon.",
    EVOLVE_INVALID_MESSAGE = "This Pokémon does not evolve.",
    EVOLVE_NOT_FOUND_MESSAGE = " evolution card not found in the evolution deck.",
    EMPTY_SLOT_MESSAGE = "The arena needs an empty slot."
  },
  arena = {
    INITIATIVE_ADVANTAGE_TOOLTIP = "Use Initiative Advantage",
    FATIGUE_INCREMENT_TOOLTIP = "Increment Battle Fatigue",
  },
  ub_control_panel = {
    BREACH_STRENGTH_TOOLTIP = "Move Ultra Beasts",
    BREACH_STRENGTH_INCREASES_MESSAGE = "The breach is growing stronger",
    ALREADY_MOVING_MESSAGE = "Ultra Beasts already moving."
  },
  teleport = {
    TELEPORT_BUTTON_TOOLTIP_1 = "Teleport to ",
    TELEPORT_BUTTON_TOOLTIP_2 = "[No Cost]"
  },
  village = {
    FLY_BUTTON_TOOLTIP_1 = "Fly to ",
    FLY_BUTTON_TOOLTIP_2 = "[Costs 1 Apricorn]",
    ALREADY_FLYING_MESSAGE = "Someone is already flying (if they are not, reloading the game should fix it)."
  },
  distortion_ore = {
    REDUCE_ORE_TOOLTIP = "Reduce Ore"
  },
  errors = {
    MISSING_DATA_NAME = "Missing Data",
    MISSING_DATA_DESCRIPTION = "Internal data for this card has been deleted. It can no longer be used in the arena. Try rewinding time.",
    TRAINER_TOKEN_NOT_FOUND = "[INFO] Could not find trainer token for player. Pick up your trainer token once, then try again.",
    OUT_OF_PLAYER_COLOURS = "[INFO] Cannot create anymore player boards, out of valid player colours.",
    CANNOT_DELETE_CENTRAL_BOARD = "[INFO] Cannot delete central player board.",
    ALL_NPC_SLOTS_OCCUPIED = "[INFO] Cannot add to the battle, all NPC slots for the arena are currently occupied."
  },
}
