#include ../config
#include ../utils

UI_SCALE = 4

--
-- Load
--

function init_dynamic_assets()
  local assets = {}
  for _, innate_ability in pairs(getObjectsWithTag(config.tags.objects.INNATE_ABILITY)) do
    table.insert(assets, {name=innate_ability.getName(), url=innate_ability.getCustomObject().image})
  end
  self.UI.setCustomAssets(assets)
end

function init_pokemon_cards_ui()
  local objects = getObjectsWithTag(config.tags.cards.POKEMON)
  for _, object in pairs(objects) do
    if object.type == "Card" then
      add({guid=object.getGUID()})
    end
  end
end

function show_ui_in_pokemon_slots()
  local pokemon_slots = getObjectsWithTag(config.tags.zones.POKEMON_SLOT)
  for _, pokemon_slot in pairs(pokemon_slots) do
    for _, object in pairs(pokemon_slot.getObjects()) do
      if object.type == "Card" and object.hasTag(config.tags.cards.POKEMON) and not object.is_face_down then
        Wait.condition(
          function() show({guid=object.getGUID(), zone=pokemon_slot}) end,
          function() return has_ui_loaded(object) end
        )
      end
    end
  end
end

function ui_boostrap()
  init_dynamic_assets()
  init_pokemon_cards_ui()
  show_ui_in_pokemon_slots()
end

function onLoad()
  pokemon_stats_store = get_module("pokemon_stats_store")
  pokemon_decks_api = get_module("pokemon_decks_api")

  Wait.condition(ui_boostrap, has_ui_loaded)
end

--
-- Utils
--

function has_any_of_tags(object, tags)
  for _, tag in pairs(tags) do
    if object.hasTag(tag) then
      return true
    end
  end
  return false
end

function get_innate_ability_name(pokemon_card)
  for _, innate_ability in pairs(getObjectsWithTag(config.tags.objects.INNATE_ABILITY)) do
    if has_any_of_tags(pokemon_card, innate_ability.getTags()) then
      return innate_ability.getName()
    end
  end
end

function count_face_down(zone)
  local count = 0
  for _, object in pairs(zone.getObjects()) do
    if object.is_face_down then
      count = count + 1
    end
  end
  return count
end

function get_guid_from_id(id)
  return string.sub(id, -6)
end

function api_func(func_name)
  return self.getGUID() .. "/" .. func_name
end

--
-- Buttons
--

function toggle_status_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})
  -- Extract, for example, "confused" from "ConfusedStatus123456"
  local status_name = string.lower(string.sub(id, 1, #id - 12))
  -- Flip 0 to 1 or 1 to 0
  pokemon_stats.status_conditions[status_name] = 1 - pokemon_stats.status_conditions[status_name]

  pokemon_stats_store.call("save", {guid=guid, pokemon_stats=pokemon_stats})
  update_ui(guid)
end

function grow_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_card.UI.setAttribute(id, "scale", ui_tuple({1.1, 1.1, 1}))
end

function shrink_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_card.UI.setAttribute(id, "scale", ui_tuple({1, 1, 1}))
end

function move_health_slider(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})
  pokemon_stats.damage = pokemon_card.getVar("health") + pokemon_stats.health_delta - tonumber(value)
  pokemon_stats_store.call("save", {guid=guid, pokemon_stats=pokemon_stats})
  update_ui(guid)
end

function click_transform_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  local current_state = pokemon_card.getStateId()
  local next_state = get_next_state(current_state, len(pokemon_card.getStates()) + 1)
  pokemon_card:setState(next_state)
end

function click_evolve_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  local evolve_into_names = {}
  for _, evolve_into_name in pairs(pokemon_card.getVar("evolve_into")) do
    table.insert(evolve_into_names, evolve_into_name)
  end

  local evolution_cards = pokemon_decks_api.call("find_pokemon_cards", {
    encounter = config.tags.encounters.EVOLUTION,
    biome     = nil,
    climate   = nil,
    names     = evolve_into_names,
  })
  for _, evolution_card in pairs(evolution_cards) do
    evolution_card.flip()
  end
  pokemon_decks_api.call("layout_pokemon_cards", {
    owner_guid    = pokemon_card.getGUID(),
    position      = pokemon_card.getPosition(),
    pokemon_cards = evolution_cards,
  })
end

function click_health_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})
  if value == "-1" then
    pokemon_stats.health_delta = pokemon_stats.health_delta + 1
  elseif value == "-2" then
    pokemon_stats.health_delta = pokemon_stats.health_delta - 1
  end
  pokemon_stats_store.call("save", {guid=guid, pokemon_stats=pokemon_stats})
  update_ui(guid)
end

function click_initiative_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})
  if value == "-1" then
    pokemon_stats.initiative_delta = pokemon_stats.initiative_delta + 1
  elseif value == "-2" then
    pokemon_stats.initiative_delta = pokemon_stats.initiative_delta - 1
  end
  pokemon_stats_store.call("save", {guid=guid, pokemon_stats=pokemon_stats})
  update_ui(guid)
end

function grow_action_buttons(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_card.UI.setAttribute("ActionButtons" .. guid, "scale", ui_tuple({1.5, 1.5, 1}))
  for _, action_type in pairs({"Confirm", "Return", "Take"}) do
    pokemon_card.UI.setAttribute(action_type .. "Action" .. guid, "interactable", true)
  end
end

function shrink_action_buttons(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_card.UI.setAttribute("ActionButtons" .. guid, "scale", ui_tuple({1, 1, 1}))
  for _, action_type in pairs({"Confirm", "Return", "Take"}) do
    pokemon_card.UI.setAttribute(action_type .. "Action" .. guid, "interactable", false)
  end
end

function click_confirm_action_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_decks_api.call("confirm_pokemon_card", {pokemon_card=pokemon_card, player=player})
end

function click_return_action_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_decks_api.call("return_pokemon_card", {pokemon_card=pokemon_card})
end

function click_take_action_button(player, value, id)
  local guid = get_guid_from_id(id)
  local pokemon_card = getObjectFromGUID(guid)
  pokemon_decks_api.call("take_pokemon_card", {pokemon_card=pokemon_card, player=player})
end

--
-- UI
--

function update_ui(guid)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})
  local pokemon_card = getObjectFromGUID(guid)
  --
  local has_states = (pokemon_card.getStates() ~= nil)
  --
  local has_evolution = (pokemon_card.getVar("evolve_into") ~= nil)
  local evolve_cost = pokemon_card.getVar("evolve_cost")
  --
  local health = pokemon_card.getVar("health") + pokemon_stats.health_delta
  local initiative = pokemon_card.getVar("initiative") + pokemon_stats.initiative_delta
  --
  local health_slider_colour = Color.ActiveGreen
  if (health - pokemon_stats.damage) <= (0.25 * health) then
    health_slider_colour = Color.ErrorRed
  elseif (health - pokemon_stats.damage) <= (0.5 * health) then
    health_slider_colour = Color.WarningYellow
  end
  --
  local health_slider_text = health - pokemon_stats.damage
  if health_slider_text <= 0 then
    health_slider_text = ""
  end
  --
  local health_button_colour = Color.AtiusBlack
  if pokemon_stats.health_delta > 0 then
    health_button_colour = Color.DeepGreen
  elseif pokemon_stats.health_delta < 0 then
    health_button_colour = Color.DeepRed
  end
  --
  local initiative_button_colour = Color.AtiusBlack
  if pokemon_stats.initiative_delta > 0 then
    initiative_button_colour = Color.DeepGreen
  elseif pokemon_stats.initiative_delta < 0 then
    initiative_button_colour = Color.DeepRed
  end
  --
  local has_fainted = (pokemon_stats.damage >= health)
  --
  pokemon_card.UI.setAttribute("TransformButton" .. guid, "active", has_states)
  pokemon_card.UI.setAttribute("EvolveButton" .. guid, "active", has_evolution)
  pokemon_card.UI.setAttribute("EvolveButton" .. guid, "text", evolve_cost)
  pokemon_card.UI.setAttribute("EvolveButton" .. guid, "textColor", ui_colour(Color.White))
  pokemon_card.UI.setAttribute("HealthSlider" .. guid, "fillColor", ui_colour(health_slider_colour))
  pokemon_card.UI.setAttribute("HealthSlider" .. guid, "maxValue", health)
  pokemon_card.UI.setAttribute("HealthSlider" .. guid, "value", health - pokemon_stats.damage)
  pokemon_card.UI.setAttribute("HealthSliderText" .. guid, "text", health_slider_text)
  pokemon_card.UI.setAttribute("HealthButtonText" .. guid, "text", health)
  pokemon_card.UI.setAttribute("HealthButtonText" .. guid, "color", ui_colour(health_button_colour))
  pokemon_card.UI.setAttribute("InitiativeButtonText" .. guid, "text", initiative)
  pokemon_card.UI.setAttribute("InitiativeButtonText" .. guid, "color", ui_colour(initiative_button_colour))
  for _, status_type in pairs({"Confused", "Paralysed", "Poisoned", "Burned", "Frozen", "Drowsy"}) do
    pokemon_card.UI.setAttribute(status_type .. "Status" .. guid, "sprite",            status_type .. "Status" .. pokemon_stats.status_conditions[string.lower(status_type)])
    pokemon_card.UI.setAttribute(status_type .. "Status" .. guid, "highlightedSprite", status_type .. "Status2")
  end
  pokemon_card.UI.setAttribute("FaintedImage" .. guid, "active", has_fainted)
end

function action_button_ui(guid, action_type, on_click_func)
  return {
    tag = "Button",
    attributes = {
      id = action_type .. "Action" .. guid,
      --
      onClick      = api_func(on_click_func),
      onMouseEnter = api_func("grow_button"),
      onMouseExit  = api_func("shrink_button"),
      interactable = false,
      --
      transition        = "SpriteSwap",
      sprite            = action_type .. "Action",
      highlightedSprite = action_type .. "ActionHighlighted",
    }
  }
end

function action_buttons_ui(guid)
  return {
    tag = "GridLayout",
    attributes = {
      anchorMin = ui_tuple({0.75/16, 20.75/28}),
      anchorMax = ui_tuple({4.25/16, 24.25/28}),
      --
      id           = "ActionButtons" .. guid,
      onMouseEnter = api_func("grow_action_buttons"),
      onMouseExit  = api_func("shrink_action_buttons"),
      --
      spacing         = ui_tuple({2, 2}),
      cellSize        = ui_tuple({100, 100}),
      childAlignment  = "MiddleCenter",
      constraint      = "FixedColumnCount",
      constraintCount = 2,
    },
    children = {
      action_button_ui(guid, "Confirm", "click_confirm_action_button"),
      action_button_ui(guid, "Return", "click_return_action_button"),
      action_button_ui(guid, "Take", "click_take_action_button"),
    }
  }
end

function transform_button_ui(guid)
  return {
    tag = "Button",
    attributes = {
      anchorMin = ui_tuple({11.75/16, 20.75/28}),
      anchorMax = ui_tuple({15.25/16, 24.25/28}),
      --
      active  = false,
      id      = "TransformButton" .. guid,
      --
      onClick           = api_func("click_transform_button"),
      transition        = "SpriteSwap",
      sprite            = "TransformButton",
      highlightedSprite = "TransformButtonHighlighted",
      pressedSprite     = "TransformButtonHighlighted",
    }
  }
end

function evolve_button_ui(guid)
  return {
    tag = "Button",
    attributes = {
      anchorMin = ui_tuple({12.75/16, 8.75/28}),
      anchorMax = ui_tuple({15.25/16, 11.25/28}),
      --
      active  = false,
      id      = "EvolveButton" .. guid,
      --
      onClick           = api_func("click_evolve_button"),
      transition        = "SpriteSwap",
      sprite            = "EvolveButton",
      highlightedSprite = "EvolveButtonHighlighted",
      pressedSprite     = "EvolveButtonHighlighted",
      --
      text                 = "?",
      textColor            = ui_colour(Color.White),
      font                 = "Fonts/La Oriental",
      resizeTextForBestFit = true,
      resizeTextMaxSize    = 80,
    }
  }
end

function stats_button_ui(guid, anchor_min, anchor_max, stat_type, on_click_func)
  return {
    tag = "Panel",
    attributes = {
      anchorMin = ui_tuple(anchor_min),
      anchorMax = ui_tuple(anchor_max),
    },
    children = {
      {
        tag = "Button",
        attributes = {
          id = stat_type .. "Button" .. guid,
          --
          onClick = api_func(on_click_func),
          sprite  = stat_type .. "Base",
        }
      },
      {
        tag = "Text",
        attributes = {
          anchorMin = ui_tuple({0.1/3.5, 0.1/2}),
          anchorMax = ui_tuple({1.9/3.5, 1.9/2}),
          --
          id = stat_type .. "ButtonText" .. guid,
          --
          text                 = "?",
          alignment            = "MiddleCenter",
          color                = ui_colour(Color.AtiusBlack),
          font                 = "Fonts/La Oriental",
          resizeTextForBestFit = true,
          resizeTextMaxSize    = 100,
        }
      },
    }
  }
end

function status_button_ui(guid, status_type)
  return {
    tag = "Button",
    attributes = {
      id = status_type .. "Status" .. guid,
      --
      onClick      = api_func("toggle_status_button"),
      onMouseEnter = api_func("grow_button"),
      onMouseExit  = api_func("shrink_button"),
      transition   = "SpriteSwap",
      sprite       = status_type .. "Status0",
    }
  }
end

function health_panel_ui(guid)
  return {
    tag = "Panel",
    attributes = {
      anchorMin = ui_tuple({0/16, 28/28}),
      anchorMax = ui_tuple({16/16, 33/28}),
      --
      active = false,
      id     = "HealthPanel" .. guid,
      --
      showAnimation = "Grow",
      hideAnimation = "Shrink",
    },
    children = {
      {
        tag = "HorizontalLayout",
        attributes = {
          anchorMin = ui_tuple({2/16, 3/5}),
          anchorMax = ui_tuple({14/16, 5/5}),
          --
          spacing        = 5,
          childAlignment = "MiddleCenter",
        },
        children = {
          status_button_ui(guid, "Confused"),
          status_button_ui(guid, "Paralysed"),
          status_button_ui(guid, "Poisoned"),
          status_button_ui(guid, "Burned"),
          status_button_ui(guid, "Frozen"),
          status_button_ui(guid, "Drowsy"),
        }
      },
      {
        tag = "Panel",
        attributes = {
          anchorMin = ui_tuple({0/16, 0/5}),
          anchorMax = ui_tuple({16/16, 3/5}),
        },
        children = {
          {
            tag = "Slider",
            attributes = {
              width  = "25%",
              height = "50%",
              --
              scale = ui_tuple({4, 2.25, 1}),
              --
              id = "HealthSlider" .. guid,
              --
              onValueChanged  = api_func("move_health_slider"),
              minValue        = 0,
              maxValue        = 0,
              wholeNumbers    = true,
              backgroundColor = ui_colour(Color.AtiusBlack),
              fillColor       = ui_colour(Color.ActiveGreen),
              handleImage     = "HealthSliderHandle",
            }
          },
          {
            tag = "Text",
            attributes = {
              anchorMin = ui_tuple({0.2/16, 0.7/3}),
              anchorMax = ui_tuple({1.8/16, 2.3/3}),
              --
              id = "HealthSliderText" .. guid,
              --
              text                 = "?",
              alignment            = "MiddleLeft",
              color                = ui_colour(Color.AtiusBlack),
              font                 = "Fonts/La Oriental",
              resizeTextForBestFit = true,
              resizeTextMaxSize    = 100,
            }
          },
          {
            tag = "Image",
            attributes = {
              anchorMin = ui_tuple({14/16, 0.5/3}),
              anchorMax = ui_tuple({16/16, 2.5/3}),
              scale     = ui_tuple({0.8, 0.8, 1}),
              --
              active = false,
              id     = "FaintedImage" .. guid,
              --
              image = "FaintedImage",
            }
          },
        }
      },
    }
  }
end

function innate_ability_image_ui(guid, innate_ability_name)
  return {
    tag = "Image",
    attributes = {
      active = false,
      id     = "InnateAbilityImage" .. guid,
      --
      image          = innate_ability_name,
      preserveAspect = true,
      --
      showAnimation = "FadeIn",
      hideAnimation = "FadeOut",
    }
  }
end

--
--
--

function add(params)
  local guid = params.guid
  local pokemon_card = getObjectFromGUID(guid)
  local innate_ability_name = get_innate_ability_name(pokemon_card)
  local pokemon_stats = pokemon_stats_store.call("get", {guid=guid})

  local WIDTH = 215
  local RATIO = 28/16

  local ui_elements = {
    {
      tag = "Panel",
      attributes = {
        width  = tostring(WIDTH * UI_SCALE),
        height = tostring(WIDTH * UI_SCALE * RATIO),
        --
        position = ui_tuple({0, 0, -25}),
        rotation = ui_tuple({0, 0, 180}),
        scale    = ui_tuple({1/UI_SCALE, (1/UI_SCALE)*0.82, 1}),
      },
      children = {
        action_buttons_ui(guid),
        transform_button_ui(guid),
        evolve_button_ui(guid),
        stats_button_ui(guid, {11.75/16, 18.25/28}, {15.25/16, 20.25/28}, "Health", "click_health_button"),
        stats_button_ui(guid, {11.75/16, 15.75/28}, {15.25/16, 17.75/28}, "Initiative", "click_initiative_button"),
        health_panel_ui(guid),
        innate_ability_image_ui(guid, innate_ability_name),
      }
    },
  }

  if len(pokemon_card.UI.getXmlTable()) == 0 then
    pokemon_card.UI.setXmlTable(ui_elements, UI.getCustomAssets())
  end

  Wait.condition(
    function() update_ui(guid) end,
    function() return has_ui_loaded(pokemon_card) end
  )
end

function show(params)
  local guid = params.guid
  local pokemon_card = getObjectFromGUID(guid)

  if not pokemon_card or len(pokemon_card.UI.getXmlTable()) == 0 then
    return
  end

  if not tobool(pokemon_card.UI.getAttribute("HealthPanel" .. guid, "active")) then
    pokemon_card.UI.show("HealthPanel" .. guid)
  end
  if not tobool(pokemon_card.UI.getAttribute("InnateAbilityImage" .. guid, "active")) and pokemon_card.UI.getAttribute("InnateAbilityImage" .. guid, "image") ~= nil then
    if params.zone ~= nil then
      pokemon_card.UI.setAttribute("InnateAbilityImage" .. guid, "position", ui_tuple({0, -1190, 30 + count_face_down(params.zone) * 50}))
    end
    pokemon_card.UI.show("InnateAbilityImage" .. guid)
  end
end

function hide(params)
  local guid = params.guid
  local pokemon_card = getObjectFromGUID(guid)

  if not pokemon_card or len(pokemon_card.UI.getXmlTable()) == 0 then
    return
  end

  pokemon_card.UI.hide("HealthPanel" .. guid)
  pokemon_card.UI.hide("InnateAbilityImage" .. guid)
end
