#include config
#include utils

PANEL_WIDTH = 350
PANEL_HEIGHT = 700

local selected_type = "Typeless"
local number_of_dice = 3
local use_full_type_chart = false

function _find_active_slots()
  local active_slots = find_objects({config.tags.property.ARENA, config.tags.zones.POKEMON_SLOT})
  local your_active_slot = get_closest(self, active_slots)

  -- Get index
  local your_active_slot_index = nil
  for i, active_slot in pairs(active_slots) do
    if active_slot == your_active_slot then
      your_active_slot_index = i
      break
    end
  end

  table.remove(active_slots, your_active_slot_index)
  local enemy_active_slot = get_closest(self, active_slots)
  return your_active_slot, enemy_active_slot
end

function onLoad()
  your_active_slot, enemy_active_slot = _find_active_slots()

  get_module("object_links_store").call("set_links", {
    object = self,
    other_objects = {
      your_active_slot,
      enemy_active_slot,
    }
  })

  function _is_ui_loaded()
    return (not self.UI.loading) and (not UI.loading)
  end
  Wait.condition(update_panel, _is_ui_loaded)
end

--
--
--

function click_type_chart_toggle(_, _, id)
  use_full_type_chart = not use_full_type_chart
  update_panel()
end

function click_type_button(_, _, id)
  selected_type = id
  update_elements()
end

function move_dice_slider(_, value, _)
  number_of_dice = tonumber(value)
  update_elements()
end

--
--
--

function get_effectiveness_panel()
  local effectiveness_panel = {
    tag = "VerticalLayout",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.2}),
      anchorMax = ui_tuple({1.0, 0.9}),
      --
      color = ui_colour(config.colours.DARK),
    },
    children = {}
  }

  local your_active_pokemon = get_object(your_active_slot)
  local types
  if not use_full_type_chart then
    if not your_active_pokemon then
      return effectiveness_panel
    end

    types = {Typeless = {}}
    local your_learnable_types = your_active_pokemon.getVar("moves")

    for _, type in pairs(your_learnable_types) do
      types[type] = config.type_chart[type]
    end
  else
    types = config.type_chart
  end

  local enemy_active_pokemon = get_object(enemy_active_slot)
  if not enemy_active_pokemon then
    return effectiveness_panel
  end

  local enemy_base_types = enemy_active_pokemon.getVar("types")
  local enemy_effectiveness = {}
  for type, effectiveness in pairs(types) do
    enemy_effectiveness[type] = 0
    for _, enemy_base_type in pairs(enemy_base_types) do
      enemy_effectiveness[type] = enemy_effectiveness[type] + (effectiveness[enemy_base_type] and effectiveness[enemy_base_type] or 0)
    end
  end

  local reverse_mapping = {}
  for type, modifier in pairs(enemy_effectiveness) do
    if reverse_mapping[modifier] == nil then
      reverse_mapping[modifier] = {}
    end
    table.insert(reverse_mapping[modifier], type)
  end

  local modifiers = {4, 2, 0, -2, -4, -6}
  for _, modifier in pairs(modifiers) do
    local types = reverse_mapping[modifier] or {}
    local modifier_group = {
      tag = "Panel",
      attributes = {
        active = (len(types) > 0),
      },
      children = {
        {
          tag = "Text",
          attributes = {
            text = signed_label(modifier),
            color = "White",
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            --
            rectAlignment = "MiddleLeft",
            width = 75,
          }
        },
        {
          tag = "GridLayout",
          attributes = {
            cellSize = use_full_type_chart and ui_tuple({40, 40}) or ui_tuple({80, 80}),
            childAlignment = "MiddleLeft",
            --
            rectAlignment = "MiddleLeft",
            offsetXY = ui_tuple({87.5, 0}),
            sizeDelta = ui_tuple({-87.5, 0}),
          },
          children = {}
        },
      },
    }
    for _, type in pairs(types) do
      local type_image = {
        tag = "Button",
        attributes = {
          id = type,
          onClick = "click_type_button",
          sprite = type,
        },
      }
      table.insert(modifier_group.children[2].children, type_image)
    end
    table.insert(effectiveness_panel.children, modifier_group)
  end
  return effectiveness_panel
end

function get_selection_panel()
  local selection_panel = {
    tag = "VerticalLayout",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.0}),
      anchorMax = ui_tuple({1.0, 0.2}),
      --
      color = ui_colour(config.colours.DARK_WOOD),
    },
    children = {
      {
        tag = "Panel",
        attributes = {
          height = 75,
        },
        children = {
          {
            tag = "Panel",
            attributes = {
              rectAlignment = "MiddleLeft",
              width = 75,
              padding = 10,
            },
            children = {
              {
                tag = "Image",
                attributes = {
                  id = "SelectedTypeImage",
                  image = selected_type,
                  preserveAspect = true,
                }
              },
            }
          },
          {
            tag = "Panel",
            attributes = {
              rectAlignment = "MiddleRight",
              width = PANEL_WIDTH - 75,
              padding = 10,
            },
            children = {
              {
                tag = "Slider",
                attributes = {
                  id = "DiceSlider",
                  onValueChanged = "move_dice_slider",
                  minValue = 1,
                  maxValue = 9,
                  value = number_of_dice,
                  wholeNumbers = true,
                  backgroundColor = ui_colour(config.colours.DARK),
                  handleImage = "HealthSliderHandle",
                }
              },
            }
          },
        }
      },
      {
        tag = "Button",
        attributes = {
          id = "RollDiceButton",
          colors = table.concat({
            ui_colour(config.colours.WOOD),
            ui_colour(config.colours.LIGHT_WOOD),
            ui_colour(config.colours.WOOD),
            ui_colour(config.colours.DARK),
          }, "|"),
          font = "Fonts/Barlow",
          resizeTextForBestFit = true,
          textAlignment = "MiddleLeft",
          icon = "AttackDice",
          iconWidth = 75,
          iconAlignment = "Right",
          padding = 10,
        }
      },
    }
  }
  return selection_panel
end

function update_panel()
  local your_active_pokemon = get_object(your_active_slot)
  if not use_full_type_chart and not your_active_pokemon then
    selected_type = "Typeless"
  end

  local ui_elements = {
    {
      tag = "Panel",
      attributes = {
        position = ui_tuple({0, 0, -11}),
        rotation = ui_tuple({0, 0, 180}),
        scale = ui_tuple({1/3.65, 1/3.65, 1}),
        width = PANEL_WIDTH,
        height = PANEL_HEIGHT,
      },
      children = {
        {
          tag = "Button",
          attributes = {
            anchorMin = ui_tuple({0.0, 0.9}),
            anchorMax = ui_tuple({1.0, 1.0}),
            --
            id = "TypeChartToggle",
            onClick = "click_type_chart_toggle",
            colors = table.concat({
              ui_colour(config.colours.WOOD),
              ui_colour(config.colours.LIGHT_WOOD),
              ui_colour(config.colours.WOOD),
              ui_colour(config.colours.DARK),
            }, "|"),
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            padding = 15,
          }
        },
      }
    },
  }
  table.insert(ui_elements[1].children, get_effectiveness_panel())
  table.insert(ui_elements[1].children, get_selection_panel())
  self.UI.setXmlTable(ui_elements, UI.getCustomAssets())

  function _is_ui_loaded()
    return (not self.UI.loading) and (not UI.loading)
  end
  Wait.condition(update_elements, _is_ui_loaded)
end

function update_elements()
  local selected_type_colour = config.colours.TYPE[selected_type]

  self.UI.setAttribute("TypeChartToggle", "text", (use_full_type_chart and "Full" or "Learnable") .. " Type Chart")
  self.UI.setAttribute("TypeChartToggle", "textColor", "White")
  self.UI.setAttribute("SelectedTypeImage", "image", selected_type)
  self.UI.setAttribute("DiceSlider", "fillColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("RollDiceButton", "text", "Roll " .. number_of_dice .. " Dice")
  self.UI.setAttribute("RollDiceButton", "iconColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("RollDiceButton", "textColor", "White")
end
