#include config
#include utils

RESOURCE_COLOUR_ORDER = {"Red", "Blue", "Yellow", "Black", "Pink", "Green", "White", "Purple"}

loaded = false

--
--
--

function _find_resource_bags()
  local resource_bags = {}
  for _, bag in pairs(getObjectsWithTag(config.tags.objects.RESOURCE_BAG)) do
    local colour = bag.getGMNotes()
    resource_bags[colour] = bag
  end
  return resource_bags
end

function onLoad()
  bag = find_closest(self, {config.tags.objects.PLAYER_BAG})
  resource_bags = _find_resource_bags()

  button_params = {
    function_owner = self,
    width          = 150,
    height         = 150,
    color          = {0, 0, 0, 0},
  }
  text_params = {
    click_function = "dummy_button",
    function_owner = self,
    scale          = {0.5, 1, 0.5},
    width          = 0,
    height         = 0,
    font_size      = 200,
    font_color     = config.colours.WHITE,
  }
  -- Resource Buttons
  for i = 0, 7 do
    button_params.click_function = "resource_button_" .. i
    self.createButton(button_params)
  end
  -- Resource Texts
  for i = 0, 7 do
    self.createButton(text_params)
  end
  loaded = true
  update_panel()
end

--
--
--

function _get_first_bag_index(colour)
  for _, resource in pairs(bag.getObjects()) do
    if resource.gm_notes == colour then
      return resource.index
    end
  end
end

function _count_resource(colour)
  local count = 0
  for _, resource in pairs(bag.getObjects()) do
    if resource.gm_notes == colour then
      count = count + 1
    end
  end
  return count
end

function resource_button_0(_, _, alt_click) resource_button(0, alt_click) end
function resource_button_1(_, _, alt_click) resource_button(1, alt_click) end
function resource_button_2(_, _, alt_click) resource_button(2, alt_click) end
function resource_button_3(_, _, alt_click) resource_button(3, alt_click) end
function resource_button_4(_, _, alt_click) resource_button(4, alt_click) end
function resource_button_5(_, _, alt_click) resource_button(5, alt_click) end
function resource_button_6(_, _, alt_click) resource_button(6, alt_click) end
function resource_button_7(_, _, alt_click) resource_button(7, alt_click) end

function resource_button(index, alt_click)
  local colour = RESOURCE_COLOUR_ORDER[index + 1]
  local resource_bag = resource_bags[colour]

  if not alt_click then
    -- Left Click: Take from resource bag, put in bag
    local resource = resource_bag.takeObject({rotation=bag.getRotation()})
    bag.putObject(resource)
  else
    local bag_index = _get_first_bag_index(colour)
    if not bag_index then
      return
    end
    -- Right Click: Take from bag, put in resource bag
    local resource = bag.takeObject({index=bag_index, rotation=bag.getRotation()})
    resource_bag.putObject(resource)
  end
end

--
--
--

function update_panel()
  if not loaded then
    return
  end
  -- Update Resource Button/Text Positions
  for i = 0, 1 do
    local index_base = 8 * i
    self.editButton({index=index_base + 0, position={-0.320, 0.2, 0.115}})
    self.editButton({index=index_base + 1, position={-0.105, 0.2, 0.115}})
    self.editButton({index=index_base + 2, position={ 0.105, 0.2, 0.115}})
    self.editButton({index=index_base + 3, position={ 0.320, 0.2, 0.115}})
    self.editButton({index=index_base + 4, position={-0.320, 0.2, 0.330}})
    self.editButton({index=index_base + 5, position={-0.105, 0.2, 0.330}})
    self.editButton({index=index_base + 6, position={ 0.105, 0.2, 0.330}})
    self.editButton({index=index_base + 7, position={ 0.320, 0.2, 0.330}})
  end
  -- Update Resource Texts
  for i = 0, 7 do
    local colour = RESOURCE_COLOUR_ORDER[i + 1]
    local count = _count_resource(colour)
    self.editButton({index = 8 + i, label = count})
  end
end
