#include config
#include utils

function onLoad()
  language_vars = get_module("localised_text_store").getTable("vars")

  self.createButton({
    click_function = "teleport",
    function_owner = self,
    position       = {0, 0.1, 0},
    width          = 600,
    height         = 600,
    color          = {0, 0, 0, 0},
    tooltip        = language_vars.teleport.TELEPORT_BUTTON_TOOLTIP_1 .. self:getName() .. "\n" .. language_vars.teleport.TELEPORT_BUTTON_TOOLTIP_2
  })
end

function find_trainer_token(player_colour)
  local trainer_tokens = getObjectsWithTag(config.tags.objects.TRAINER)
  for _, trainer_token in pairs(trainer_tokens) do
    if trainer_token.getColorTint() == Color.fromString(player_colour) then
      return trainer_token
    end
  end
end

function teleport(_, player_colour)
  local trainer_token = find_trainer_token(player_colour)
  if not trainer_token then
    broadcastToAll(language_vars.errors.TRAINER_TOKEN_NOT_FOUND, Color.InfoBlue)
    return
  end

  function teleport_coroutine()
    local target_pos = self:getPosition() + Vector(0, 0.2, 0)
    -- Enter
    trainer_token:setLock(true)
    trainer_token:setPositionSmooth(trainer_token:getPosition() - Vector(0, 1, 0), false, true)
    while trainer_token:isSmoothMoving() do coroutine.yield(0) end
    -- Teleport
    trainer_token:setPosition(target_pos - Vector(0, 1, 0))
    -- Exit
    trainer_token:setPositionSmooth(target_pos, false, false)
    while trainer_token:isSmoothMoving() do coroutine.yield(0) end
    trainer_token:setLock(false)
    return 1
  end
  startLuaCoroutine(self, "teleport_coroutine")
end
