#include config
#include utils

ENCOUNTER_COLOURS = {
  [config.tags.encounters.WEAK]      = Color.WeakGreen,
  [config.tags.encounters.MODERATE]  = Color.ModerateBlue,
  [config.tags.encounters.STRONG]    = Color.StrongRed,
  [config.tags.encounters.LEGENDARY] = Color.LegendaryYellow,
}

local search_params = {}
local search_button_hide_timer_id

function onLoad()
  Wait.condition(load_panel, has_ui_loaded)
end

function get_player()
  for _, player in pairs(Player.getPlayers()) do
    if self.getColorTint() == Color.fromString(player.color) then
      return player
    end
  end
end

--
--
--

function player_has_artifact(sanctuary_name)
  local player = get_player()
  if not player then
    return false
  end
  local hand = player.getHandTransform(1)
  if not hand then
    return false
  end
  local player_pokemon_zones = {find_closest(hand.position, {config.tags.zones.POKEMON_SLOT}, "Scripting", 6)}

  for _, zone in pairs(player_pokemon_zones) do
    for _, object in pairs(zone.getObjects(true)) do
      if object.hasTag(config.tags.items.ARTIFACT) then
        for artifact_sactuary_name in split(object.getGMNotes(), "/") do
          if artifact_sactuary_name == sanctuary_name then
            return true
          end
        end
      end
    end
  end
  return false
end

function find_search_params()
  local hit_list = Physics.cast({
    origin       = self.getPosition(),
    direction    = {0, -1, 0},
    type         = 2,
    size         = {1.5, 1.5, 1.5},
    max_distance = 2,
  })
  for _, hit_info in ipairs(hit_list) do
    local hit_object = hit_info.hit_object
    -- Campaign Tokens
    if hit_object.hasTag(config.tags.world.CAMPAIGN) then
      break
    -- Sanctuaries
    elseif hit_object.hasTag(config.tags.world.SANCTUARY) and player_has_artifact(hit_object.getName()) then
      set_search_params(hit_object)
      show_search_button()
      break
    -- Encounters
    elseif hit_object.hasTag(config.tags.world.ENCOUNTER) and not hit_object.is_face_down then
      set_search_params(hit_object)
      show_search_button()
      break
    end
  end
end

function set_search_params(hit_object)
  local tags = hit_object.getTags()

  search_params = {
    encounter = get_encounter_tag(tags),
    biome = get_biome_tag(tags),
    climate = get_climate_tag(tags),
    name = hit_object.getGMNotes(),
  }
end

-- local legendary_names = split(hit_object.getGMNotes(), "/")
-- for legendary_name in legendary_names do
--   log(legendary_name)
-- end

--
--
--

function update_colour_tint(player_colour)
  -- Clear player colour from other trainer tokens
  local trainer_tokens = getObjectsWithTag(config.tags.objects.TRAINER)
  for _, trainer_token in pairs(trainer_tokens) do
    if trainer_token.getColorTint() == Color.fromString(player_colour) then
      trainer_token.setColorTint({0, 0, 0, 0.25})
    end
  end
  -- Set on this token
  self.setColorTint(player_colour)
end

function spawn_hand_zone()
  print("!")
  spawnObject({
    type              = "HandTrigger",
    position          = self.getPosition() + Vector(0, 5, 0),
    rotation          = self.getRotation(),
    scale             = Vector(18, 5, 6.5),
    sound             = false,
    callback_function = function(hand)
      hand.setValue("Brown")
    end,
  })
end

--
--
--

function onPickUp(player_colour)
  hide_search_button(0)
  update_colour_tint(player_colour)
end

function onDrop()
  Wait.condition(find_search_params, function() return self.resting end, 2)
end

--
--
--

function show_search_button()
  update_panel()
  self.UI.show("SearchButton")
  hide_search_button(5)
end

function hide_search_button(delay)
  if search_button_hide_timer_id then
    Wait.stop(search_button_hide_timer_id)
    search_button_hide_timer_id = nil
  end

  function hide()
    self.UI.hide("SearchButton")
    search_button_hide_timer_id = nil
  end
  search_button_hide_timer_id = Wait.time(hide, delay)
end

function click_search_button()
  hide_search_button(0)
  spawn_hand_zone()
end

--
--
--

function load_panel()
  local ui_elements = {
    {
      tag = "Panel",
      attributes = {
        position = ui_tuple({0, 0, -650}),
        rotation = ui_tuple({270, 0, 0}),
        scale    = ui_tuple({1, 1, 1}),
        width    = 250,
        height   = 500,
      },
      children = {
        tag = "Button",
        attributes = {
          active  = false,
          id      = "SearchButton",
          onClick = "click_search_button",
          -- onMouseEnter = "enter_relocate_button",
          -- onMouseExit  = "exit_relocate_button",
          --
          color = ui_colour(Color(0, 0, 0, 0)),
          --
          textShadow           = ui_colour(Color.AtiusBlack),
          textOutline          = ui_colour(Color.AtiusBlack),
          font                 = "Fonts/La Oriental",
          resizeTextMaxSize    = 500,
          resizeTextForBestFit = true,
          --
          showAnimation = "Grow",
          hideAnimation = "Shrink",
        },
      }
    },
  }
  self.UI.setXmlTable(ui_elements, UI.getCustomAssets())

  Wait.condition(update_panel, has_ui_loaded)
end

function update_panel()
  self.UI.setAttribute("SearchButton", "color", search_params.encounter and ui_colour(ENCOUNTER_COLOURS[search_params.encounter]) or ui_colour(Color(0, 0, 0, 0)))
  self.UI.setAttribute("SearchButton", "text", "!")
  self.UI.setAttribute("SearchButton", "textColor", ui_colour(Color.White))
end
