--
-- UTILS START
--

MODULE_LANGUAGE_TAG = "Module Language"

CLIMATE_TAGS = {"Cold", "Temperate", "Warm"}
BIOME_TAGS = {"Plains", "Forest", "Mountain", "Ocean"}
ENCOUNTER_TAGS = {"Weak", "Moderate", "Strong", "Legendary", "Distortion", "Secret"}


function load_module(module_tag)
  local modules = getObjectsWithTag(module_tag)
  if len(modules) > 1 then
    print('More than one module with tag "' .. module_tag .. '".')
    return
  elseif len(modules) == 0 then
    print('Missing a module with tag "' .. module_tag .. '".')
    return
  end
  local module = modules[1]
  return module:getTable("vars")
end

function get_module(module_name)
  local modules = {}
  for _, module in pairs(getObjectsWithTag("Module")) do
    modules[module.getGMNotes()] = module
  end
  return modules[module_name]
end

function dummy_button() end

function tobool(value)
  if value == "true" or value == 1 then
    return true
  elseif value == "false" or value == 0 then
    return false
  end
  return value
end

function len(t)
  l = 0
  for _, _ in pairs(t) do
    l = l + 1
  end
  return l
end

function get_keys(t)
  local keys = {}
  for key, _ in pairs(t) do
    table.insert(keys, key)
  end
  return keys
end

function find_first_index(t, value)
  for i, value_ in pairs(t) do
    if value_ == value then
      return i
    end
  end
end

function contains(t, value)
  local first_index = find_first_index(t, value)
  return first_index != nil
end

function get_min_key_and_value(t)
  local key, min = nil, math.huge
  for k, v in pairs(t) do
      if t[k] < min then
          key, min = k, v
      end
  end
  return key, min
end

function get_max_key_and_value(t)
  local key, max = nil, -math.huge
  for k, v in pairs(t) do
      if t[k] > max then
          key, max = k, v
      end
  end
  return key, max
end

local function reversedipairsiter(t, i)
  i = i - 1
  if i ~= 0 then return i, t[i] end
end
function reversedipairs(t) return reversedipairsiter, t, #t + 1 end

function shuffle(t)
  shuffled = {}
  for i, value in ipairs(t) do
  	local j = math.random(1, #shuffled + 1)
  	table.insert(shuffled, j, value)
  end
  return shuffled
end

function get_object_infos_from_zone_deck(zone, shuffle)
  local object_infos = {}
  for _, zone_deck in pairs(zone:getObjects()) do
    if zone_deck.type == "Card" then
      table.insert(object_infos, {
        description = zone_deck:getDescription(),
        gm_notes = zone_deck:getGMNotes(),
        guid = zone_deck:getGUID(),
        index = 1,
        lua_script = zone_deck:getLuaScript(),
        lua_script_state = zone_deck.script_state,
        memo = zone_deck.memo,
        name = zone_deck:getName(),
        tags = zone_deck:getTags()
      })
    elseif zone_deck.type == "Deck" then
      if shuffle then zone_deck:randomize() end
      for _, object_info in pairs(zone_deck:getObjects()) do
        table.insert(object_infos, object_info)
      end
    end
  end
  return object_infos
end

function take_object_from_zone_deck(zone, params)
  for _, zone_deck in pairs(zone:getObjects()) do
    if zone_deck.type == "Card" and zone_deck:getGUID() == params.guid then
      zone_deck:setPosition(params.position)
      zone_deck:setRotation(params.rotation)
      return zone_deck
    elseif zone_deck.type == "Deck" then
      for _, card in pairs(zone_deck:getObjects()) do
        if card.guid == params.guid then
          return zone_deck:takeObject(params)
        end
      end
    end
  end
end

function get_biome_tag(tags)
  for _, tag in pairs(shuffle(tags)) do
    if contains(BIOME_TAGS, tag) then
      return tag
    end
  end
end

function get_climate_tag(tags)
  for _, tag in pairs(shuffle(tags)) do
    if contains(CLIMATE_TAGS, tag) then
      return tag
    end
  end
end

function get_encounter_tag(tags)
  for _, encounter_tag in pairs(config.tags.encounters) do
    if contains(tags, encounter_tag) then
      return encounter_tag
    end
  end
end

function brief_pause()
  for i = 0, 25 do
    coroutine.yield(0)
  end
end

function ui_loading_pause(object)
  while object.UI.loading do
    coroutine.yield(0)
  end
end

function signed_label(value)
  if not value then return nil end
  return (value >= 0) and "+" .. value or value
end

function get_next_state(current_state, total_states, alt_click)
  if not current_state then
    return 1
  end
  local state_step = not alt_click and 1 or -1
  return ((current_state - 1 + state_step) % total_states) + 1
end

function round(value)
  return math.floor(value + 0.5)
end

function get_object(zone)
  local objects = zone:getObjects()
  for _, object in pairs(objects) do
    return object
  end
end

function get_x_dir(obj)
  return round(math.cos(math.rad(obj:getRotation().x)))
end

function get_y_dir(obj)
  return round(math.cos(math.rad(obj:getRotation().y)))
end

function get_z_dir(obj)
  return round(math.cos(math.rad(obj:getRotation().z)))
end

function flip_object(obj, known_height)
  local height = known_height
  if not height then
    height = obj:getBounds().size.y
  end
  local new_pos = Vector(obj:getPosition().x, obj:getPosition().y + height * get_z_dir(obj), obj:getPosition().z)
  obj:setPosition(new_pos)
  local new_rot = obj:getRotation() + Vector(0, 0, 180)
  obj:setRotation(new_rot)
end

function double_check_then(condition, f)
  if not condition() then
    return false
  end
  function double_check_coroutine()
    brief_pause()
    if condition() then
      f()
    end
    return 1
  end
  startLuaCoroutine(self, "double_check_coroutine")
end

function register_button(buttons, name)
  buttons[name] = len(buttons)
end

function get_closest(caller, objects)
  -- Given a table of objects, return the closest object to the caller
  local distances = {}
  for _, object in pairs(objects) do
    distances[object] = caller.getPosition():distance(object.getPosition())
  end

  local closest_object, _ = get_min_key_and_value(distances)
  return closest_object
end

function filter_objects_of_type(objects, type)
  local objects_of_type = {}
  for _, object in pairs(objects) do
    if object.type == type then
      table.insert(objects_of_type, object)
    end
  end
  return objects_of_type
end

function find_objects(tags, type)
  local objects = getObjectsWithAllTags(tags)
  if type == nil then
    return objects
  end
  return filter_objects_of_type(objects, type)
end

function find_closest(caller, tags, type)
  local objects = find_objects(tags, type)
  return get_closest(caller, objects)
end

function ui_tuple(t)
  return table.concat(t, " ")
end

function ui_colour(colour)
  return "#" .. colour:toHex()
end

--
-- UTILS END
--
