#include ../config
#include ../utils

PANEL_WIDTH = 350
PANEL_HEIGHT = 700

FATIGUE_VALUE_MAX = 5

local calculated_modifiers = {Typeless = 0}
local finished_dice = {}
local post_roll_wait_condition_id

local selected_type = "Typeless"
local number_of_dice = 3
local use_full_type_chart = false

function _set_fatigue_dice_rotation_values()
  local rotation_values = fatigue_dice.getRotationValues()
  for state, data in pairs(rotation_values) do
    rotation_values[state].rotation = Vector(data.rotation.x, 180 - self.getRotation().y, data.rotation.z)
  end
  fatigue_dice.setRotationValues(rotation_values)
end

function onLoad()
  position = self.getPosition()
  dice_bag = find_closest(position, {config.tags.objects.ATTACK_DICE}, "Infinite")
  fatigue_dice = find_closest(position, {config.tags.objects.FATIGUE_DICE})
  field_zone = find_closest(position, {config.tags.objects.POKEMON_MODEL}, "Scripting")
  your_active_slot, enemy_active_slot = find_closest(position, {config.tags.property.ARENA, config.tags.zones.POKEMON_SLOT}, "Scripting", 2)

  get_module("object_links_store").call("set_links", {
    object = self,
    other_objects = {
      dice_bag,
      fatigue_dice,
      field_zone,
      your_active_slot,
      enemy_active_slot,
    }
  })

  _set_fatigue_dice_rotation_values()
  Wait.condition(update_panel, has_ui_loaded)
end

--
--
--

function cleanup_dice()
  local attack_dice_list = find_objects({config.tags.objects.ATTACK_DICE}, "Dice")
  for _, attack_dice in pairs(attack_dice_list) do
    attack_dice.destroyObject()
  end
end

function animate_model()
  local models = field_zone.getObjects()
  for _, model in pairs(models) do
    model.AssetBundle.playTriggerEffect(1)
  end
end

function is_fatigued()
  return fatigue_dice.getRotationValue() == FATIGUE_VALUE_MAX
end

function reset_fatigue_dice()
  fatigue_dice.setValue(1)
end

function increment_fatigue_dice()
  local current_value = fatigue_dice.getRotationValue()
  local new_value = current_value + 1
  if current_value < FATIGUE_VALUE_MAX then
    fatigue_dice.setRotationValue(new_value)
  end
end

--
--
--

function add_forces_to_dice(dice, direction)
  if dice.isDestroyed() then return end
  --
  dice.addForce(Vector(0, 0, direction * 20))
  dice.addTorque(Vector(math.random() * 5000, math.random() * 5000, math.random() * 5000))
end

function adjust_dice(dice)
  if dice.isDestroyed() then return end
  --
  local rotation = dice.getRotation()
  dice.setRotationSmooth(Vector(round(rotation.x / 90) * 90, rotation.y, round(rotation.z / 90) * 90))
end

function print_dice_result()
  local results = {
    ["Status Symbol"] = {["count"] = 0, ["damage"] = 0, ["symbol"] = "[0]"},
    ["Regular Hit"]   = {["count"] = 0, ["damage"] = 1, ["symbol"] = "[1]"},
    ["Critical Hit"]  = {["count"] = 0, ["damage"] = 2, ["symbol"] = "[2]"},
  }
  for _, dice in pairs(finished_dice) do
    local result = dice.getRotationValue()
    results[result].count = results[result].count + 1
  end

  local base_damage = 0
  local base_string = "Roll: "

  local result_strings = {}
  for result, data in pairs(results) do
    base_damage = base_damage + data.count * data.damage
    table.insert(result_strings, data.count .. "•" .. data.symbol)
  end
  base_string = base_string .. table.concat(result_strings, " + ")

  base_damage = base_damage + calculated_modifiers[selected_type]
  base_string = base_string .. " (" .. signed_label(calculated_modifiers[selected_type]) .. ")"
  base_string = base_string .. " = " .. base_damage

  broadcastToAll(base_string, Color[selected_type])
  if is_fatigued() then
    broadcastToAll("Fatigued: Take 3 Damage", Color.ErrorRed)
  end
end

function roll_callback(dice, direction)
  Wait.frames(function()
    add_forces_to_dice(dice, direction)
    Wait.condition(
      function() adjust_dice(dice) end,
      function() return dice.isDestroyed() or dice.resting end
    )
  end, 10)
end

--
--
--

function click_type_chart_toggle(_, _, id)
  use_full_type_chart = not use_full_type_chart
  reset_panel()
  update_panel()
end

function click_type_button(_, _, id)
  selected_type = id
  update_elements()
end

function move_dice_slider(_, value, _)
  number_of_dice = tonumber(value)
  update_elements()
end

function click_roll_button()
  if post_roll_wait_condition_id then
    Wait.stop(post_roll_wait_condition_id)
  end
  finished_dice = {}
  cleanup_dice()
  animate_model()

  local direction = math.cos(math.rad(field_zone.getRotation().y))
  local z_offset = direction * 1
  local x_offset = -direction * (number_of_dice - 1) / 2

  local number_of_dice_to_spawn = number_of_dice

  for _ = 1, number_of_dice_to_spawn do
    local spawned_dice = dice_bag.takeObject({
      position          = field_zone.getPosition() + Vector(x_offset, 0.1, z_offset),
      rotation          = Vector(math.random(1, 4) * 90, math.random(1, 4) * 90, math.random(1, 4) * 90),
      smooth            = false,
      callback_function = function(dice)
        roll_callback(dice, direction)
      end
    })
    -- Colour the attack dice
    spawned_dice.setColorTint(Color[selected_type])
    spawned_dice.highlightOn(Color[selected_type])

    x_offset = x_offset + direction * 1
  end
  post_roll_wait_condition_id = Wait.condition(post_roll, function() return len(finished_dice) == number_of_dice_to_spawn end)
end

function post_roll()
  -- Increment the fatigue dice if an enemy Pokémon is present
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if enemy_active_pokemon then
    increment_fatigue_dice()
  end
  print_dice_result()
end

--
--
--

function get_effectiveness_panel()
  local effectiveness_panel = {
    tag = "VerticalLayout",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.2}),
      anchorMax = ui_tuple({1.0, 0.9}),
      --
      color = ui_colour(Color.AtiusBlack),
    },
    children = {}
  }

  local your_active_pokemon = get_object(your_active_slot, true)
  local types
  if not use_full_type_chart then
    if not your_active_pokemon then
      return effectiveness_panel
    end

    types = {Typeless = {}}
    local your_learnable_types = your_active_pokemon.getVar("moves")

    for _, type in pairs(your_learnable_types) do
      types[type] = config.type_chart[type]
    end
  else
    types = config.type_chart
  end

  local enemy_base_types = {"Typeless"}
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if enemy_active_pokemon then
    enemy_base_types = enemy_active_pokemon.getVar("types")
  end

  local enemy_effectiveness = {}
  for type, effectiveness in pairs(types) do
    enemy_effectiveness[type] = 0
    for _, enemy_base_type in pairs(enemy_base_types) do
      enemy_effectiveness[type] = enemy_effectiveness[type] + (effectiveness[enemy_base_type] and effectiveness[enemy_base_type] or 0)
    end
  end

  local reverse_mapping = {}
  for type, modifier in pairs(enemy_effectiveness) do
    if reverse_mapping[modifier] == nil then
      reverse_mapping[modifier] = {}
    end
    table.insert(reverse_mapping[modifier], type)
  end

  calculated_modifiers = {}
  for _, modifier in pairs({4, 2, 0, -2, -4, -6}) do
    local types = reverse_mapping[modifier] or {}
    local modifier_group = {
      tag = "Panel",
      attributes = {
        active = (len(types) > 0),
      },
      children = {
        {
          tag = "Text",
          attributes = {
            text = signed_label(modifier),
            color = "White",
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            --
            rectAlignment = "MiddleLeft",
            width = 75,
          }
        },
        {
          tag = "GridLayout",
          attributes = {
            cellSize = use_full_type_chart and ui_tuple({40, 40}) or ui_tuple({80, 80}),
            childAlignment = "MiddleLeft",
            --
            rectAlignment = "MiddleLeft",
            offsetXY = ui_tuple({87.5, 0}),
            sizeDelta = ui_tuple({-87.5, 0}),
          },
          children = {}
        },
      },
    }
    for _, type in pairs(types) do
      local type_image = {
        tag = "Button",
        attributes = {
          id = type,
          onClick = "click_type_button",
          sprite = type,
        },
      }
      table.insert(modifier_group.children[2].children, type_image)
      calculated_modifiers[type] = modifier
    end
    table.insert(effectiveness_panel.children, modifier_group)
  end
  return effectiveness_panel
end

function get_selection_panel()
  local selection_panel = {
    tag = "VerticalLayout",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.0}),
      anchorMax = ui_tuple({1.0, 0.2}),
      --
      color = ui_colour(Color.WoodDark),
    },
    children = {
      {
        tag = "Panel",
        attributes = {
          height = 75,
        },
        children = {
          {
            tag = "Panel",
            attributes = {
              rectAlignment = "MiddleLeft",
              width = 75,
              padding = 10,
            },
            children = {
              {
                tag = "Image",
                attributes = {
                  id = "SelectedTypeImage",
                  image = selected_type,
                  preserveAspect = true,
                }
              },
            }
          },
          {
            tag = "Panel",
            attributes = {
              rectAlignment = "MiddleRight",
              width = PANEL_WIDTH - 75,
              padding = 10,
            },
            children = {
              {
                tag = "Slider",
                attributes = {
                  id = "DiceSlider",
                  onValueChanged = "move_dice_slider",
                  minValue = 1,
                  maxValue = 9,
                  value = number_of_dice,
                  wholeNumbers = true,
                  backgroundColor = ui_colour(Color.AtiusBlack),
                  handleImage = "HealthSliderHandle",
                }
              },
            }
          },
        }
      },
      {
        tag = "Button",
        attributes = {
          id = "RollDiceButton",
          onClick = "click_roll_button",
          colors = table.concat({
            ui_colour(Color.Wood),
            ui_colour(Color.WoodLight),
            ui_colour(Color.Wood),
            ui_colour(Color.AtiusBlack),
          }, "|"),
          font = "Fonts/Barlow",
          resizeTextForBestFit = true,
          textAlignment = "MiddleLeft",
          icon = "AttackDice",
          iconWidth = 50,
          iconAlignment = "Right",
          padding = 10,
        }
      },
    }
  }
  return selection_panel
end

function reset_panel()
  selected_type = "Typeless"
  number_of_dice = 3
end

function update_panel()
  local your_active_pokemon = get_object(your_active_slot, true)
  if not your_active_pokemon then
    if not use_full_type_chart then
      reset_panel()
    end
    cleanup_dice()
    reset_fatigue_dice()
  end

  local ui_elements = {
    {
      tag = "Panel",
      attributes = {
        position = ui_tuple({0, 0, -11}),
        rotation = ui_tuple({0, 0, 180}),
        scale = ui_tuple({1/3.65, 1/3.65, 1}),
        width = PANEL_WIDTH,
        height = PANEL_HEIGHT,
      },
      children = {
        {
          tag = "Button",
          attributes = {
            anchorMin = ui_tuple({0.0, 0.9}),
            anchorMax = ui_tuple({1.0, 1.0}),
            --
            id = "TypeChartToggle",
            onClick = "click_type_chart_toggle",
            colors = table.concat({
              ui_colour(Color.Wood),
              ui_colour(Color.WoodLight),
              ui_colour(Color.Wood),
              ui_colour(Color.AtiusBlack),
            }, "|"),
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            padding = 15,
          }
        },
      }
    },
  }
  table.insert(ui_elements[1].children, get_effectiveness_panel())
  table.insert(ui_elements[1].children, get_selection_panel())
  self.UI.setXmlTable(ui_elements, UI.getCustomAssets())

  Wait.condition(update_elements, has_ui_loaded)
end

function update_elements()
  local selected_type_colour = Color[selected_type]

  self.UI.setAttribute("TypeChartToggle", "text", (use_full_type_chart and "Full" or "Learnable") .. " Type Chart")
  self.UI.setAttribute("TypeChartToggle", "textColor", "White")
  self.UI.setAttribute("SelectedTypeImage", "image", selected_type)
  self.UI.setAttribute("DiceSlider", "fillColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("RollDiceButton", "text", "Roll " .. number_of_dice .. " " .. selected_type .. " Dice")
  self.UI.setAttribute("RollDiceButton", "iconColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("RollDiceButton", "textColor", "White")
end
