#include ../config
#include ../utils

PANEL_WIDTH = 350
PANEL_HEIGHT = 700

MAX_FATIGUE_LEVEL = 5

local calculated_modifiers = {Typeless = 0}

local selected_type = "Typeless"
local number_of_dice = 3
local use_full_type_chart = false
local fatigue_level = 0

function onLoad(save_state)
  local saved_fatigue_level = JSON.decode(save_state)
  if saved_fatigue_level then
    fatigue_level = saved_fatigue_level
  end

  position = self.getPosition()
  dice_bag = find_closest(position, {config.tags.objects.ATTACK_DICE}, "Infinite")
  field_zone = find_closest(position, {config.tags.objects.POKEMON_MODEL}, "Scripting")
  your_active_slot, enemy_active_slot = find_closest(position, {config.tags.property.ARENA, config.tags.zones.POKEMON_SLOT}, "Scripting", 2)

  get_module("object_links_store").call("set_links", {
    object = self,
    other_objects = {
      dice_bag,
      field_zone,
      your_active_slot,
      enemy_active_slot,
    }
  })

  Wait.condition(update_panel, has_ui_loaded)
end

function onSave()
  return JSON.encode(fatigue_level)
end

--
--
--

function cleanup_dice()
  local attack_dice_list = find_objects({config.tags.objects.ATTACK_DICE}, "Dice")
  for _, attack_dice in pairs(attack_dice_list) do
    attack_dice.destroyObject()
  end
end

function animate_model()
  local models = field_zone.getObjects()
  for _, model in pairs(models) do
    model.AssetBundle.playTriggerEffect(1)
  end
end

--
--
--

function add_forces_to_dice(dice, direction)
  if dice.isDestroyed() then return end
  --
  dice.addForce(Vector(0, 0, direction * 20))
  dice.addTorque(Vector(math.random() * 5000, math.random() * 5000, math.random() * 5000))
end

function adjust_dice(dice)
  if dice.isDestroyed() then return end
  --
  local rotation = dice.getRotation()
  dice.setRotationSmooth(Vector(round(rotation.x / 90) * 90, rotation.y, round(rotation.z / 90) * 90))
end

function roll_callback(dice, direction)
  Wait.frames(function()
    add_forces_to_dice(dice, direction)
    Wait.condition(
      function() adjust_dice(dice) end,
      function() return dice.isDestroyed() or dice.resting end
    )
  end, 10)
end

--
--
--

function fatigue_truncate_number_of_dice()
  local max_number_of_dice = 9 - fatigue_level
  if number_of_dice > max_number_of_dice then
    number_of_dice = max_number_of_dice
  end
end

function click_type_chart_toggle(_, _, id)
  use_full_type_chart = not use_full_type_chart
  reset_selections()
  update_panel()
end

function click_type_button(_, _, id)
  selected_type = id
  update_elements()
end

function move_dice_slider(_, value, _)
  number_of_dice = tonumber(value)
  fatigue_truncate_number_of_dice()
  update_elements()
end

function click_fatigue_button(_, value, _)
  if value == "-1" and fatigue_level < MAX_FATIGUE_LEVEL then
    fatigue_level = fatigue_level + 1
    fatigue_truncate_number_of_dice()
  elseif value == "-2" and fatigue_level > 0 then
    fatigue_level = fatigue_level - 1
  end
  update_elements()
end

function click_roll_button()
  cleanup_dice()
  animate_model()

  local direction = math.cos(math.rad(field_zone.getRotation().y))
  local z_offset = direction * 1
  local x_offset = -direction * (number_of_dice - 1) / 2

  local number_of_dice_to_spawn = number_of_dice

  for _ = 1, number_of_dice_to_spawn do
    local spawned_dice = dice_bag.takeObject({
      position          = field_zone.getPosition() + Vector(x_offset, 0.1, z_offset),
      rotation          = Vector(math.random(1, 4) * 90, math.random(1, 4) * 90, math.random(1, 4) * 90),
      smooth            = false,
      callback_function = function(dice)
        roll_callback(dice, direction)
      end
    })
    -- Colour the attack dice
    spawned_dice.setColorTint(Color[selected_type])
    spawned_dice.highlightOn(Color[selected_type])

    x_offset = x_offset + direction * 1
  end
  -- Increment the fatigue dice if an enemy Pokémon is present
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if enemy_active_pokemon and fatigue_level < MAX_FATIGUE_LEVEL then
    fatigue_level = fatigue_level + 1
    fatigue_truncate_number_of_dice()
  end

  update_elements()
end

--
--
--

function get_effectiveness_panel()
  local effectiveness_panel = {
    tag = "VerticalLayout",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.2}),
      anchorMax = ui_tuple({1.0, 0.9}),
      --
      color = ui_colour(Color.AtiusBlack),
    },
    children = {}
  }

  local your_active_pokemon = get_object(your_active_slot, true)
  local types
  if not use_full_type_chart then
    if not your_active_pokemon then
      return effectiveness_panel
    end

    types = {Typeless = {}}
    local your_learnable_types = your_active_pokemon.getVar("moves")

    for _, type in pairs(your_learnable_types) do
      types[type] = config.type_chart[type]
    end
  else
    types = config.type_chart
  end

  local enemy_base_types = {"Typeless"}
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if enemy_active_pokemon then
    enemy_base_types = enemy_active_pokemon.getVar("types")
  end

  local enemy_effectiveness = {}
  for type, effectiveness in pairs(types) do
    enemy_effectiveness[type] = 0
    for _, enemy_base_type in pairs(enemy_base_types) do
      enemy_effectiveness[type] = enemy_effectiveness[type] + (effectiveness[enemy_base_type] and effectiveness[enemy_base_type] or 0)
    end
  end

  local reverse_mapping = {}
  for type, modifier in pairs(enemy_effectiveness) do
    if reverse_mapping[modifier] == nil then
      reverse_mapping[modifier] = {}
    end
    table.insert(reverse_mapping[modifier], type)
  end

  calculated_modifiers = {}
  for _, modifier in pairs({4, 2, 0, -2, -4, -6}) do
    local types = reverse_mapping[modifier] or {}
    local modifier_group = {
      tag = "Panel",
      attributes = {
        active = (len(types) > 0),
      },
      children = {
        {
          tag = "Text",
          attributes = {
            text = signed_label(modifier),
            color = "White",
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            --
            rectAlignment = "MiddleLeft",
            width = 75,
          }
        },
        {
          tag = "GridLayout",
          attributes = {
            cellSize = use_full_type_chart and ui_tuple({40, 40}) or ui_tuple({80, 80}),
            childAlignment = "MiddleLeft",
            --
            rectAlignment = "MiddleLeft",
            offsetXY = ui_tuple({87.5, 0}),
            sizeDelta = ui_tuple({-87.5, 0}),
          },
          children = {}
        },
      },
    }
    for _, type in pairs(types) do
      local type_image = {
        tag = "Button",
        attributes = {
          id = type,
          onClick = "click_type_button",
          sprite = type,
        },
      }
      table.insert(modifier_group.children[2].children, type_image)
      calculated_modifiers[type] = modifier
    end
    table.insert(effectiveness_panel.children, modifier_group)
  end
  return effectiveness_panel
end

function get_selection_panel()
  local selection_panel = {
    tag = "Panel",
    attributes = {
      anchorMin = ui_tuple({0.0, 0.0}),
      anchorMax = ui_tuple({1.0, 0.2}),
      --
      color = ui_colour(Color.WoodDark),
    },
    children = {
      {
        tag = "Panel",
        attributes = {
          anchorMin = ui_tuple({0.0, 0.5}),
          anchorMax = ui_tuple({1.0, 1.0}),
        },
        children = {
          {
            tag = "ProgressBar",
            attributes = {
              width = PANEL_WIDTH,
              --
              id = "FatigueBar",
              --
              color              = ui_colour(Color.AtiusBlackLight),
              fillImageColor     = ui_colour(Color.AtiusBlack),
              percentage         = 90,
              showPercentageText = false,
            },
          },
          {
            tag = "Slider",
            attributes = {
              width = (PANEL_WIDTH / 3),
              scale = ui_tuple({3, 3, 1}),
              --
              id = "DiceSlider",
              onValueChanged = "move_dice_slider",
              minValue = 1,
              maxValue = 10,
              value = number_of_dice,
              wholeNumbers = true,
              backgroundColor = ui_colour(Color.Clear),
              handleImage = selected_type,
            }
          },
          {
            tag = "Button",
            attributes = {
              anchorMin = ui_tuple({0.9, 0.28}),
              anchorMax = ui_tuple({1.0, 0.72}),
              --
              id = "FatigueButton",
              --
              onClick = "click_fatigue_button",
              image   = "FatigueButton",
              --
              text                 = "0",
              font                 = "Fonts/La Oriental",
              resizeTextForBestFit = true,
            },
          },
        }
      },
      {
        tag = "Panel",
        attributes = {
          anchorMin = ui_tuple({0.0, 0.0}),
          anchorMax = ui_tuple({1.0, 0.5}),
        },
        children = {
          {
            tag = "Button",
            attributes = {
              id = "RollDiceButton",
              onClick = "click_roll_button",
              colors = table.concat({
                ui_colour(Color.Wood),
                ui_colour(Color.WoodLight),
                ui_colour(Color.Wood),
                ui_colour(Color.AtiusBlack),
              }, "|"),
              text = "?",
              font = "Fonts/Barlow",
              resizeTextForBestFit = true,
              textAlignment = "MiddleLeft",
              icon = "AttackDice",
              iconWidth = 50,
              iconAlignment = "Right",
              padding = 10,
            }
          },
        }
      },
    }
  }
  return selection_panel
end

function reset_selections()
  selected_type = "Typeless"
  number_of_dice = 3
end

function reload_panel()
  local your_active_pokemon = get_object(your_active_slot, true)
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if your_active_pokemon and enemy_active_pokemon then
    return
  end

  if not use_full_type_chart then
    reset_selections()
  end
  fatigue_level = 0
  cleanup_dice()
  load_panel()
end

function load_panel()
  local ui_elements = {
    {
      tag = "Panel",
      attributes = {
        position = ui_tuple({0, 0, -11}),
        rotation = ui_tuple({0, 0, 180}),
        scale = ui_tuple({1/3.65, 1/3.65, 1}),
        width = PANEL_WIDTH,
        height = PANEL_HEIGHT,
      },
      children = {
        {
          tag = "Button",
          attributes = {
            anchorMin = ui_tuple({0.0, 0.9}),
            anchorMax = ui_tuple({1.0, 1.0}),
            --
            id = "TypeChartToggle",
            onClick = "click_type_chart_toggle",
            colors = table.concat({
              ui_colour(Color.Wood),
              ui_colour(Color.WoodLight),
              ui_colour(Color.Wood),
              ui_colour(Color.AtiusBlack),
            }, "|"),
            font = "Fonts/Barlow",
            resizeTextForBestFit = true,
            padding = 15,
          }
        },
      }
    },
  }
  table.insert(ui_elements[1].children, get_effectiveness_panel())
  table.insert(ui_elements[1].children, get_selection_panel())
  self.UI.setXmlTable(ui_elements, UI.getCustomAssets())

  Wait.condition(update_elements, has_ui_loaded)
end

function update_panel()
  Wait.time(reload_panel, 1)

  local your_active_pokemon = get_object(your_active_slot, true)
  local enemy_active_pokemon = get_object(enemy_active_slot, true)
  if not your_active_pokemon or not enemy_active_pokemon then
    return
  end

  load_panel()
end

function update_elements()
  local selected_type_colour = Color[selected_type]

  self.UI.setAttribute("TypeChartToggle", "text", (use_full_type_chart and "Full" or "Learnable") .. " Type Chart")
  self.UI.setAttribute("TypeChartToggle", "textColor", "White")
  self.UI.setAttribute("FatigueBar", "percentage", 95 - 9 * (fatigue_level + 1))
  self.UI.setAttribute("DiceSlider", "handleImage", selected_type)
  self.UI.setAttribute("DiceSlider", "fillColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("DiceSlider", "value", number_of_dice)
  self.UI.setAttribute("FatigueButton", "text", tostring(fatigue_level))
  self.UI.setAttribute("FatigueButton", "textColor", ui_colour(Color.ErrorRed))
  self.UI.setAttribute("RollDiceButton", "text", "Roll " .. number_of_dice .. " " .. selected_type)
  self.UI.setAttribute("RollDiceButton", "iconColor", ui_colour(selected_type_colour))
  self.UI.setAttribute("RollDiceButton", "textColor", ui_colour(Color.White))
end
