#include ../config
#include ../utils

local button_state

function onLoad(save_state)
  button_state = JSON.decode(save_state)

  if not button_state then
    button_state = {active = false}
  end

  Wait.condition(load_panel, has_ui_loaded)
end

function onSave()
  return JSON.encode(button_state)
end

--
--
--

function click_active_button()
  button_state.active = not button_state.active
  update_panel()
end

function load_panel()
  local ui_elements = {
    {
      tag = "Button",
      attributes = {
        id      = "ActiveButton",
        onClick = "click_active_button",
        --
        position = ui_tuple({0, 0, -11}),
        width    = 65,
        height   = 65,
        --
        sprite = "MoveActive",
        color  = ui_colour(Color(1, 1, 1, 0))
      }
    },
  }
  self.UI.setXmlTable(ui_elements, UI.getCustomAssets())

  Wait.condition(update_panel, has_ui_loaded)
end

function update_panel()
  local colour = ui_colour(Color(1, 1, 1, button_state.active and 1 or 0))
  self.UI.setAttribute("ActiveButton", "color", colour)
end
